### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by codemasterlike** [zhoumy96/react-pdf-large-files#1]
Dear Zhoumy96,
Thanks very much for sharing.
I have tried many time, but still not able to run it in localhost.
What I did is:

1. download code
2. move download code to desktop, cd to the download folder
3. yarn install 
4. yarn preview

The result:
In command: Hello@alos-MacBook-Pro 3b % yarn preview
yarn run v1.22.19
$ vite preview
  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose

In http://localhost:4173/
Cannot GET /

Appreciate your help please.
Thank you very much.

**Comment by zhoumy96** [comment]
please try yarn dev

**Comment by zhoumy96** [comment]
> Dear Zhoumy96, Thanks very much for sharing. I have tried many time, but still not able to run it in localhost. What I did is:
> 
> 1. download code
> 2. move download code to desktop, cd to the download folder
> 3. yarn install
> 4. yarn preview
> 
> The result: In command: Hello@alos-MacBook-Pro 3b % yarn preview yarn run v1.22.19 $ vite preview ➜ Local: http://localhost:4173/ ➜ Network: use --host to expose
> 
> In http://localhost:4173/ Cannot GET /
> 
> Appreciate your help please. Thank you very much.
please try yarn dev

**Comment by codemasterlike** [comment]
Thanks very much
